MCU = atmega32u4
F_CPU = 8000000
ARCH = AVR8
F_USB = $(F_CPU)
BOOTLOADER = caterina
SPLIT_KEYBOARD = yes

EXTRAKEY_ENABLE = yes
COMBO_ENABLE = yes
RGBLIGHT_ENABLE = yes
UNICODE_ENABLE = yes

EXTRAFLAGS += -flto
LTO_ENABLE = yes
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
